# -*- mode: ruby -*-
# vi: set ft=ruby :

# Sources:
# https://gist.github.com/santrancisco/a7183470efa0e3412222670d0bfb3da5
# Tero Karvinen Himself and; https://terokarvinen.com/2018/automatically-provision-vagrant-virtualmachines-as-salt-slaves/
# Niko Heiskanen: https://heiskanen.rocks/server_management/h1 

# Provision Debian-based
$minion = <<MINION
apt update -y
sudo apt install bash-completion -y
apt install salt-minion -qy
sed -i 's/\#master\:.*/master\:\ 192.168.1.25/g' /etc/salt/minion
echo "saltenv: dev"|sudo tee -a /etc/salt/minion
systemctl restart salt-minion
MINION

# Provision Fedora
$fedora = <<FEDORA
dnf check-update -y
sudo dnf install bash-completion -y
dnf install salt-minion -qy
sed -i 's/\#master\:.*/master\:\ 192.168.1.25/g' /etc/salt/minion
echo "saltenv: dev"|sudo tee -a /etc/salt/minion
systemctl restart salt-minion
FEDORA

$minion_count = 2

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
    (1..$minion_count).each do |i|
      config.vm.define "dev-server#{i}" do |dev|
        dev.vm.provision "final", type: "shell", inline: $minion
        dev.vm.hostname = "dev-server#{i}"
        dev.vm.network :private_network, type: "dhcp"
        dev.vm.synced_folder '.', '/vagrant', disabled: true
	    dev.vm.provider "virtualbox" do |v|
          v.memory = 512
          v.cpus = 1
          v.name = "Dev-Server#{i}"
        end
      end
  end

# Create Fedora
  config.vm.define "dev-fedora-ws" do |fedora|
    fedora.vm.box = "fedora/36-cloud-base"
    fedora.vm.hostname = "dev-fedora-ws"
    fedora.vm.network :private_network, ip: "192.168.56.103"
    fedora.vm.provision "shell", inline: $fedora
	fedora.vm.synced_folder '.', '/vagrant', disabled: true
	fedora.vm.provider :virtualbox do |vb|
      vb.name = "dev-fedora-ws"
      vb.memory = 1028
      vb.cpus = 1
      vb.customize ["modifyvm", :id, "--vram", "32"]
    end 
  end
  
# Create Ubuntu
  config.vm.define "dev-ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/jammy64"
    ubuntu.vm.hostname = "dev-ubuntu"
    ubuntu.vm.network :private_network, ip: "192.168.56.104"
    ubuntu.vm.provision "shell", inline: $minion
	ubuntu.vm.synced_folder '.', '/vagrant', disabled: true
	ubuntu.vm.provider :virtualbox do |vb|
      vb.name = "dev-ubuntu"
      vb.memory = 1028
      vb.cpus = 1
      vb.customize ["modifyvm", :id, "--vram", "16"]
    end 
  end
end

